
package oracle.iam.connectors.sap.cup.ws.audit;
 
import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "getAuditLogs_com.virsa.ae.core.BOException", targetNamespace = "urn:SAPGRC_AC_IDM_AUDITTRAILWsd/SAPGRC_AC_IDM_AUDITTRAILVi")
public class GetAuditLogsComVirsaAeCoreBOExceptionDoc
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BOException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetAuditLogsComVirsaAeCoreBOExceptionDoc(String message, BOException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetAuditLogsComVirsaAeCoreBOExceptionDoc(String message, BOException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: examples.webservices.simple_client.audittrial.BOException
     */
    public BOException getFaultInfo() {
        return faultInfo;
    }

}
