 
package oracle.iam.connectors.sap.cup.ws.getstatus;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SAPGRC_AC_IDM_REQUESTSTATUSVi_Document", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSWsd/SAPGRC_AC_IDM_REQUESTSTATUSVi/document")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SAPGRCACIDMREQUESTSTATUSViDocument {


    /**
     * 
     * @param requestId
     * @param language
     * @return
     *     returns examples.webservices.simple_client.requeststatus.RequestStatusDTO
     * @throws GetStatusComVirsaAeCoreBOExceptionDoc
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi")
    @RequestWrapper(localName = "getStatus", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi", className = "oracle.iam.connectors.sap.cup.ws.getstatus.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi", className = "oracle.iam.connectors.sap.cup.ws.getstatus.GetStatusResponse")
    public RequestStatusDTO getStatus(
        @WebParam(name = "requestId", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi")
        String requestId,
        @WebParam(name = "language", targetNamespace = "urn:SAPGRC_AC_IDM_REQUESTSTATUSVi")
        String language)
        throws GetStatusComVirsaAeCoreBOExceptionDoc
    ;

}
