 
package oracle.iam.connectors.sap.cup.ws.submitreq;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.3-06/19/2008 07:03 PM(bt)
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SAPGRC_AC_IDM_SUBMITREQUESTVi_Document", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTWsd/SAPGRC_AC_IDM_SUBMITREQUESTVi/document")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SAPGRCACIDMSUBMITREQUESTViDocument {


    /**
     * 
     * @param requestDetails
     * @return
     *     returns oracle.iam.connectors.sap.cup.ws.submitreq.RequestSubmissionResult
     */
    @WebMethod
    @WebResult(name = "Response", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi")
    @RequestWrapper(localName = "getSubmitRequest", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi", className = "oracle.iam.connectors.sap.cup.ws.submitreq.GetSubmitRequest")
    @ResponseWrapper(localName = "getSubmitRequestResponse", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi", className = "oracle.iam.connectors.sap.cup.ws.submitreq.GetSubmitRequestResponse")
    public RequestSubmissionResult getSubmitRequest(
        @WebParam(name = "requestDetails", targetNamespace = "urn:SAPGRC_AC_IDM_SUBMITREQUESTVi")
        RequestDetailsData requestDetails);

}
